name = "GamersMagicated"
author = "Gamers"
version = "1.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b6ddae0d50621f9d0d308047ed6cc417ec6b25009e6ccf2b87e41cb2f1fb8a7"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
