name = "GamersMagicated"
author = "Gamers"
version = "1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6726e93ac03de00875b7d6afe22b9af617a48d04621d98553d8454892a51a3f4"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
