name = "GamersMagicated"
author = "Gamers"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a40f33523b22103ec0c92de99ece2f416506853a09f2e95da75d5c0928dd941c"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
