name = "GamersMagicated"
author = "Gamers"
version = "0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e654d1ec2839d3730635fa7d2e3ab5c112638911f0c0cfce6de5c73ecb81b48"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
