name = "GamersMagicated"
author = "Gamers"
version = "1.10.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "242d4159e43187a169ed8344a0880b2f8852bff459d40fbdb7190b2d2c2c6597"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
