name = "GamersMagicated"
author = "Gamers"
version = "1.5.HF1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d143bad53f8dc4b8a4743fdd3e01850b066f3359acb6619fb7afcdf157b41410"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
