name = "GamersMagicated"
author = "Gamers"
version = "1.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d921367c39fc4e4754596361782d38ffa71737e36f140ade2769746269c2f8c"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
