name = "GamersMagicated"
author = "Gamers"
version = "1.7.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b9cdffb2ad43d1b3eb3589ed18d650d801c6a7f43af13e4f3ad60464dedcc44"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
