name = "GamersMagicated"
author = "Gamers"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "901ecc3e22d0af08667cdc816501a2078d2cca031535cf4d8845d414a40debaf"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
