name = "GamersMagicated"
author = "Gamers"
version = "0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e431cfc3cf8f3441ec28185c4279d598a1cac227d806cd06aea31377cd16825"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
