name = "GamersMagicated"
author = "Gamers"
version = "0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "443f2889492205496a60b658b5bce58e1c92ef738c7eb0a24c2c51f374b4d8c1"

[versions]
minecraft = "1.18.2"
quilt = "0.17.4"
