name = "GamersMagicated"
author = "Gamers"
version = "1.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48c9aeea54c021b8244c519be9f23f434326449c9eb9fc285fc3aa97483141b2"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
