name = "GamersMagicated"
author = "Gamers"
version = "1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1fb4f7c0d451ea75ac35d2247f4254224b62c0ee7c2417795bf11bc0474f8c"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
